### ISSUE TITLE
question / pull request in the main project

### ISSUE THREAD

**Issue by cokelaer** [jdidion/cutadapt-parallel#1]
Hi, I'm interested by your parallel implementation and  was wondering if it has been submitted to cutadapt pull request and if there are any caveats I should be aware of before testing your code in production. thanks

**Comment by jdidion** [comment]
Hi Thomas, I tried to get my changes integrated into cutadapt but it hasn't worked out so I have forked the project and added a lot of other new features besides. You can try out the beta version at jdidion/atropos. I am submitting the paper very soon. The parallel implementation should be ready for production, but the new insert-alignment algorithm for paired-ends reads is still being tested. I plan to release 1.1 around the end of the year, at which point I will consider it fully production-ready. But I would be grateful for bug reports and improvement requests in the meantime.

**Comment by jdidion** [comment]
https://github.com/jdidion/atropos

**Comment by cokelaer** [comment]
looks nice. thanks. I will do some tests in the following days.
